// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.github.xy02.raas;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raas.Request)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    long getSessionId();

    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 2;</code>
     */
    java.lang.String getClientId();
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 3;</code>
     */
    com.google.protobuf.ByteString getBin();
  }
  /**
   * Protobuf type {@code raas.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageLite<
          Request, Request.Builder> implements
      // @@protoc_insertion_point(message_implements:raas.Request)
      RequestOrBuilder {
    private Request() {
      clientId_ = "";
      bin_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void setSessionId(long value) {
      
      sessionId_ = value;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void clearSessionId() {
      
      sessionId_ = 0L;
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 2;
    private java.lang.String clientId_;
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 2;</code>
     */
    public java.lang.String getClientId() {
      return clientId_;
    }
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(clientId_);
    }
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 2;</code>
     */
    private void setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
    }
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 2;</code>
     */
    private void clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
    }
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 2;</code>
     */
    private void setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value.toStringUtf8();
    }

    public static final int BIN_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bin_;
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 3;</code>
     */
    public com.google.protobuf.ByteString getBin() {
      return bin_;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 3;</code>
     */
    private void setBin(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bin_ = value;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 3;</code>
     */
    private void clearBin() {
      
      bin_ = getDefaultInstance().getBin();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0L) {
        output.writeInt64(1, sessionId_);
      }
      if (!clientId_.isEmpty()) {
        output.writeString(2, getClientId());
      }
      if (!bin_.isEmpty()) {
        output.writeBytes(3, bin_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      if (!clientId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getClientId());
      }
      if (!bin_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bin_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.xy02.raas.Data.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.xy02.raas.Data.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.xy02.raas.Data.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.xy02.raas.Data.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code raas.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.xy02.raas.Data.Request, Builder> implements
        // @@protoc_insertion_point(builder_implements:raas.Request)
        com.github.xy02.raas.Data.RequestOrBuilder {
      // Construct using com.github.xy02.raas.Data.Request.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public long getSessionId() {
        return instance.getSessionId();
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder setSessionId(long value) {
        copyOnWrite();
        instance.setSessionId(value);
        return this;
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        copyOnWrite();
        instance.clearSessionId();
        return this;
      }

      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 2;</code>
       */
      public java.lang.String getClientId() {
        return instance.getClientId();
      }
      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        return instance.getClientIdBytes();
      }
      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 2;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        copyOnWrite();
        instance.setClientId(value);
        return this;
      }
      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 2;</code>
       */
      public Builder clearClientId() {
        copyOnWrite();
        instance.clearClientId();
        return this;
      }
      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 2;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 3;</code>
       */
      public com.google.protobuf.ByteString getBin() {
        return instance.getBin();
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 3;</code>
       */
      public Builder setBin(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBin(value);
        return this;
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 3;</code>
       */
      public Builder clearBin() {
        copyOnWrite();
        instance.clearBin();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:raas.Request)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.xy02.raas.Data.Request();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.xy02.raas.Data.Request other = (com.github.xy02.raas.Data.Request) arg1;
          sessionId_ = visitor.visitLong(sessionId_ != 0L, sessionId_,
              other.sessionId_ != 0L, other.sessionId_);
          clientId_ = visitor.visitString(!clientId_.isEmpty(), clientId_,
              !other.clientId_.isEmpty(), other.clientId_);
          bin_ = visitor.visitByteString(bin_ != com.google.protobuf.ByteString.EMPTY, bin_,
              other.bin_ != com.google.protobuf.ByteString.EMPTY, other.bin_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  sessionId_ = input.readInt64();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  clientId_ = s;
                  break;
                }
                case 26: {

                  bin_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.xy02.raas.Data.Request.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:raas.Request)
    private static final com.github.xy02.raas.Data.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Request();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.xy02.raas.Data.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Request> PARSER;

    public static com.google.protobuf.Parser<Request> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ServerOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raas.ServerOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    long getSessionId();

    /**
     * <pre>
     *sequence number start from 1
     * </pre>
     *
     * <code>optional int64 server_output_sequence = 2;</code>
     */
    long getServerOutputSequence();

    /**
     * <pre>
     *server id,  server only need to send it once. if client request with output, server should send it immediately
     * </pre>
     *
     * <code>optional string server_id = 6;</code>
     */
    java.lang.String getServerId();
    /**
     * <pre>
     *server id,  server only need to send it once. if client request with output, server should send it immediately
     * </pre>
     *
     * <code>optional string server_id = 6;</code>
     */
    com.google.protobuf.ByteString
        getServerIdBytes();

    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 7;</code>
     */
    com.google.protobuf.ByteString getBin();

    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional bytes ping = 8;</code>
     */
    com.google.protobuf.ByteString getPing();

    /**
     * <pre>
     *end with final binary data, nullable
     * </pre>
     *
     * <code>optional bytes end = 9;</code>
     */
    com.google.protobuf.ByteString getEnd();

    /**
     * <pre>
     *end with error message
     * </pre>
     *
     * <code>optional string err = 10;</code>
     */
    java.lang.String getErr();
    /**
     * <pre>
     *end with error message
     * </pre>
     *
     * <code>optional string err = 10;</code>
     */
    com.google.protobuf.ByteString
        getErrBytes();

    public com.github.xy02.raas.Data.ServerOutput.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code raas.ServerOutput}
   */
  public  static final class ServerOutput extends
      com.google.protobuf.GeneratedMessageLite<
          ServerOutput, ServerOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:raas.ServerOutput)
      ServerOutputOrBuilder {
    private ServerOutput() {
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite {
      SERVER_ID(6),
      BIN(7),
      PING(8),
      END(9),
      ERR(10),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 6: return SERVER_ID;
          case 7: return BIN;
          case 8: return PING;
          case 9: return END;
          case 10: return ERR;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    private void clearBody() {
      bodyCase_ = 0;
      body_ = null;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void setSessionId(long value) {
      
      sessionId_ = value;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void clearSessionId() {
      
      sessionId_ = 0L;
    }

    public static final int SERVER_OUTPUT_SEQUENCE_FIELD_NUMBER = 2;
    private long serverOutputSequence_;
    /**
     * <pre>
     *sequence number start from 1
     * </pre>
     *
     * <code>optional int64 server_output_sequence = 2;</code>
     */
    public long getServerOutputSequence() {
      return serverOutputSequence_;
    }
    /**
     * <pre>
     *sequence number start from 1
     * </pre>
     *
     * <code>optional int64 server_output_sequence = 2;</code>
     */
    private void setServerOutputSequence(long value) {
      
      serverOutputSequence_ = value;
    }
    /**
     * <pre>
     *sequence number start from 1
     * </pre>
     *
     * <code>optional int64 server_output_sequence = 2;</code>
     */
    private void clearServerOutputSequence() {
      
      serverOutputSequence_ = 0L;
    }

    public static final int SERVER_ID_FIELD_NUMBER = 6;
    /**
     * <pre>
     *server id,  server only need to send it once. if client request with output, server should send it immediately
     * </pre>
     *
     * <code>optional string server_id = 6;</code>
     */
    public java.lang.String getServerId() {
      java.lang.String ref = "";
      if (bodyCase_ == 6) {
        ref = (java.lang.String) body_;
      }
      return ref;
    }
    /**
     * <pre>
     *server id,  server only need to send it once. if client request with output, server should send it immediately
     * </pre>
     *
     * <code>optional string server_id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      java.lang.String ref = "";
      if (bodyCase_ == 6) {
        ref = (java.lang.String) body_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *server id,  server only need to send it once. if client request with output, server should send it immediately
     * </pre>
     *
     * <code>optional string server_id = 6;</code>
     */
    private void setServerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 6;
      body_ = value;
    }
    /**
     * <pre>
     *server id,  server only need to send it once. if client request with output, server should send it immediately
     * </pre>
     *
     * <code>optional string server_id = 6;</code>
     */
    private void clearServerId() {
      if (bodyCase_ == 6) {
        bodyCase_ = 0;
        body_ = null;
      }
    }
    /**
     * <pre>
     *server id,  server only need to send it once. if client request with output, server should send it immediately
     * </pre>
     *
     * <code>optional string server_id = 6;</code>
     */
    private void setServerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyCase_ = 6;
      body_ = value.toStringUtf8();
    }

    public static final int BIN_FIELD_NUMBER = 7;
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 7;</code>
     */
    public com.google.protobuf.ByteString getBin() {
      if (bodyCase_ == 7) {
        return (com.google.protobuf.ByteString) body_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 7;</code>
     */
    private void setBin(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 7;
      body_ = value;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 7;</code>
     */
    private void clearBin() {
      if (bodyCase_ == 7) {
        bodyCase_ = 0;
        body_ = null;
      }
    }

    public static final int PING_FIELD_NUMBER = 8;
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional bytes ping = 8;</code>
     */
    public com.google.protobuf.ByteString getPing() {
      if (bodyCase_ == 8) {
        return (com.google.protobuf.ByteString) body_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional bytes ping = 8;</code>
     */
    private void setPing(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 8;
      body_ = value;
    }
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional bytes ping = 8;</code>
     */
    private void clearPing() {
      if (bodyCase_ == 8) {
        bodyCase_ = 0;
        body_ = null;
      }
    }

    public static final int END_FIELD_NUMBER = 9;
    /**
     * <pre>
     *end with final binary data, nullable
     * </pre>
     *
     * <code>optional bytes end = 9;</code>
     */
    public com.google.protobuf.ByteString getEnd() {
      if (bodyCase_ == 9) {
        return (com.google.protobuf.ByteString) body_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     *end with final binary data, nullable
     * </pre>
     *
     * <code>optional bytes end = 9;</code>
     */
    private void setEnd(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 9;
      body_ = value;
    }
    /**
     * <pre>
     *end with final binary data, nullable
     * </pre>
     *
     * <code>optional bytes end = 9;</code>
     */
    private void clearEnd() {
      if (bodyCase_ == 9) {
        bodyCase_ = 0;
        body_ = null;
      }
    }

    public static final int ERR_FIELD_NUMBER = 10;
    /**
     * <pre>
     *end with error message
     * </pre>
     *
     * <code>optional string err = 10;</code>
     */
    public java.lang.String getErr() {
      java.lang.String ref = "";
      if (bodyCase_ == 10) {
        ref = (java.lang.String) body_;
      }
      return ref;
    }
    /**
     * <pre>
     *end with error message
     * </pre>
     *
     * <code>optional string err = 10;</code>
     */
    public com.google.protobuf.ByteString
        getErrBytes() {
      java.lang.String ref = "";
      if (bodyCase_ == 10) {
        ref = (java.lang.String) body_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *end with error message
     * </pre>
     *
     * <code>optional string err = 10;</code>
     */
    private void setErr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 10;
      body_ = value;
    }
    /**
     * <pre>
     *end with error message
     * </pre>
     *
     * <code>optional string err = 10;</code>
     */
    private void clearErr() {
      if (bodyCase_ == 10) {
        bodyCase_ = 0;
        body_ = null;
      }
    }
    /**
     * <pre>
     *end with error message
     * </pre>
     *
     * <code>optional string err = 10;</code>
     */
    private void setErrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyCase_ = 10;
      body_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0L) {
        output.writeInt64(1, sessionId_);
      }
      if (serverOutputSequence_ != 0L) {
        output.writeInt64(2, serverOutputSequence_);
      }
      if (bodyCase_ == 6) {
        output.writeString(6, getServerId());
      }
      if (bodyCase_ == 7) {
        output.writeBytes(
            7, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 8) {
        output.writeBytes(
            8, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 9) {
        output.writeBytes(
            9, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 10) {
        output.writeString(10, getErr());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      if (serverOutputSequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, serverOutputSequence_);
      }
      if (bodyCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getServerId());
      }
      if (bodyCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              7, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 8) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              8, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 9) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              9, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getErr());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.xy02.raas.Data.ServerOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.ServerOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.xy02.raas.Data.ServerOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code raas.ServerOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.xy02.raas.Data.ServerOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:raas.ServerOutput)
        com.github.xy02.raas.Data.ServerOutputOrBuilder {
      // Construct using com.github.xy02.raas.Data.ServerOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public BodyCase
          getBodyCase() {
        return instance.getBodyCase();
      }

      public Builder clearBody() {
        copyOnWrite();
        instance.clearBody();
        return this;
      }


      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public long getSessionId() {
        return instance.getSessionId();
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder setSessionId(long value) {
        copyOnWrite();
        instance.setSessionId(value);
        return this;
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        copyOnWrite();
        instance.clearSessionId();
        return this;
      }

      /**
       * <pre>
       *sequence number start from 1
       * </pre>
       *
       * <code>optional int64 server_output_sequence = 2;</code>
       */
      public long getServerOutputSequence() {
        return instance.getServerOutputSequence();
      }
      /**
       * <pre>
       *sequence number start from 1
       * </pre>
       *
       * <code>optional int64 server_output_sequence = 2;</code>
       */
      public Builder setServerOutputSequence(long value) {
        copyOnWrite();
        instance.setServerOutputSequence(value);
        return this;
      }
      /**
       * <pre>
       *sequence number start from 1
       * </pre>
       *
       * <code>optional int64 server_output_sequence = 2;</code>
       */
      public Builder clearServerOutputSequence() {
        copyOnWrite();
        instance.clearServerOutputSequence();
        return this;
      }

      /**
       * <pre>
       *server id,  server only need to send it once. if client request with output, server should send it immediately
       * </pre>
       *
       * <code>optional string server_id = 6;</code>
       */
      public java.lang.String getServerId() {
        return instance.getServerId();
      }
      /**
       * <pre>
       *server id,  server only need to send it once. if client request with output, server should send it immediately
       * </pre>
       *
       * <code>optional string server_id = 6;</code>
       */
      public com.google.protobuf.ByteString
          getServerIdBytes() {
        return instance.getServerIdBytes();
      }
      /**
       * <pre>
       *server id,  server only need to send it once. if client request with output, server should send it immediately
       * </pre>
       *
       * <code>optional string server_id = 6;</code>
       */
      public Builder setServerId(
          java.lang.String value) {
        copyOnWrite();
        instance.setServerId(value);
        return this;
      }
      /**
       * <pre>
       *server id,  server only need to send it once. if client request with output, server should send it immediately
       * </pre>
       *
       * <code>optional string server_id = 6;</code>
       */
      public Builder clearServerId() {
        copyOnWrite();
        instance.clearServerId();
        return this;
      }
      /**
       * <pre>
       *server id,  server only need to send it once. if client request with output, server should send it immediately
       * </pre>
       *
       * <code>optional string server_id = 6;</code>
       */
      public Builder setServerIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServerIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 7;</code>
       */
      public com.google.protobuf.ByteString getBin() {
        return instance.getBin();
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 7;</code>
       */
      public Builder setBin(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBin(value);
        return this;
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 7;</code>
       */
      public Builder clearBin() {
        copyOnWrite();
        instance.clearBin();
        return this;
      }

      /**
       * <pre>
       *PING
       * </pre>
       *
       * <code>optional bytes ping = 8;</code>
       */
      public com.google.protobuf.ByteString getPing() {
        return instance.getPing();
      }
      /**
       * <pre>
       *PING
       * </pre>
       *
       * <code>optional bytes ping = 8;</code>
       */
      public Builder setPing(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPing(value);
        return this;
      }
      /**
       * <pre>
       *PING
       * </pre>
       *
       * <code>optional bytes ping = 8;</code>
       */
      public Builder clearPing() {
        copyOnWrite();
        instance.clearPing();
        return this;
      }

      /**
       * <pre>
       *end with final binary data, nullable
       * </pre>
       *
       * <code>optional bytes end = 9;</code>
       */
      public com.google.protobuf.ByteString getEnd() {
        return instance.getEnd();
      }
      /**
       * <pre>
       *end with final binary data, nullable
       * </pre>
       *
       * <code>optional bytes end = 9;</code>
       */
      public Builder setEnd(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEnd(value);
        return this;
      }
      /**
       * <pre>
       *end with final binary data, nullable
       * </pre>
       *
       * <code>optional bytes end = 9;</code>
       */
      public Builder clearEnd() {
        copyOnWrite();
        instance.clearEnd();
        return this;
      }

      /**
       * <pre>
       *end with error message
       * </pre>
       *
       * <code>optional string err = 10;</code>
       */
      public java.lang.String getErr() {
        return instance.getErr();
      }
      /**
       * <pre>
       *end with error message
       * </pre>
       *
       * <code>optional string err = 10;</code>
       */
      public com.google.protobuf.ByteString
          getErrBytes() {
        return instance.getErrBytes();
      }
      /**
       * <pre>
       *end with error message
       * </pre>
       *
       * <code>optional string err = 10;</code>
       */
      public Builder setErr(
          java.lang.String value) {
        copyOnWrite();
        instance.setErr(value);
        return this;
      }
      /**
       * <pre>
       *end with error message
       * </pre>
       *
       * <code>optional string err = 10;</code>
       */
      public Builder clearErr() {
        copyOnWrite();
        instance.clearErr();
        return this;
      }
      /**
       * <pre>
       *end with error message
       * </pre>
       *
       * <code>optional string err = 10;</code>
       */
      public Builder setErrBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:raas.ServerOutput)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.xy02.raas.Data.ServerOutput();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.xy02.raas.Data.ServerOutput other = (com.github.xy02.raas.Data.ServerOutput) arg1;
          sessionId_ = visitor.visitLong(sessionId_ != 0L, sessionId_,
              other.sessionId_ != 0L, other.sessionId_);
          serverOutputSequence_ = visitor.visitLong(serverOutputSequence_ != 0L, serverOutputSequence_,
              other.serverOutputSequence_ != 0L, other.serverOutputSequence_);
          switch (other.getBodyCase()) {
            case SERVER_ID: {
              body_ = visitor.visitOneofString(
                 bodyCase_ == 6, body_, other.body_);
              break;
            }
            case BIN: {
              body_ = visitor.visitOneofByteString(
                  bodyCase_ == 7, body_, other.body_);
              break;
            }
            case PING: {
              body_ = visitor.visitOneofByteString(
                  bodyCase_ == 8, body_, other.body_);
              break;
            }
            case END: {
              body_ = visitor.visitOneofByteString(
                  bodyCase_ == 9, body_, other.body_);
              break;
            }
            case ERR: {
              body_ = visitor.visitOneofString(
                 bodyCase_ == 10, body_, other.body_);
              break;
            }
            case BODY_NOT_SET: {
              visitor.visitOneofNotSet(bodyCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.bodyCase_ != 0) {
              bodyCase_ = other.bodyCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  sessionId_ = input.readInt64();
                  break;
                }
                case 16: {

                  serverOutputSequence_ = input.readInt64();
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();
                  bodyCase_ = 6;
                  body_ = s;
                  break;
                }
                case 58: {
                  bodyCase_ = 7;
                  body_ = input.readBytes();
                  break;
                }
                case 66: {
                  bodyCase_ = 8;
                  body_ = input.readBytes();
                  break;
                }
                case 74: {
                  bodyCase_ = 9;
                  body_ = input.readBytes();
                  break;
                }
                case 82: {
                  String s = input.readStringRequireUtf8();
                  bodyCase_ = 10;
                  body_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.xy02.raas.Data.ServerOutput.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:raas.ServerOutput)
    private static final com.github.xy02.raas.Data.ServerOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServerOutput();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.xy02.raas.Data.ServerOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ServerOutput> PARSER;

    public static com.google.protobuf.Parser<ServerOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ClientOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raas.ClientOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    long getSessionId();

    /**
     * <pre>
     *sequence number start from 1
     * </pre>
     *
     * <code>optional int64 client_output_sequence = 2;</code>
     */
    long getClientOutputSequence();

    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 7;</code>
     */
    com.google.protobuf.ByteString getBin();

    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional bytes pong = 8;</code>
     */
    com.google.protobuf.ByteString getPong();

    /**
     * <pre>
     *end with final binary data, nullable
     * </pre>
     *
     * <code>optional bytes end = 9;</code>
     */
    com.google.protobuf.ByteString getEnd();

    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 10;</code>
     */
    java.lang.String getCancel();
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 10;</code>
     */
    com.google.protobuf.ByteString
        getCancelBytes();

    public com.github.xy02.raas.Data.ClientOutput.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code raas.ClientOutput}
   */
  public  static final class ClientOutput extends
      com.google.protobuf.GeneratedMessageLite<
          ClientOutput, ClientOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:raas.ClientOutput)
      ClientOutputOrBuilder {
    private ClientOutput() {
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite {
      BIN(7),
      PONG(8),
      END(9),
      CANCEL(10),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 7: return BIN;
          case 8: return PONG;
          case 9: return END;
          case 10: return CANCEL;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    private void clearBody() {
      bodyCase_ = 0;
      body_ = null;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void setSessionId(long value) {
      
      sessionId_ = value;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void clearSessionId() {
      
      sessionId_ = 0L;
    }

    public static final int CLIENT_OUTPUT_SEQUENCE_FIELD_NUMBER = 2;
    private long clientOutputSequence_;
    /**
     * <pre>
     *sequence number start from 1
     * </pre>
     *
     * <code>optional int64 client_output_sequence = 2;</code>
     */
    public long getClientOutputSequence() {
      return clientOutputSequence_;
    }
    /**
     * <pre>
     *sequence number start from 1
     * </pre>
     *
     * <code>optional int64 client_output_sequence = 2;</code>
     */
    private void setClientOutputSequence(long value) {
      
      clientOutputSequence_ = value;
    }
    /**
     * <pre>
     *sequence number start from 1
     * </pre>
     *
     * <code>optional int64 client_output_sequence = 2;</code>
     */
    private void clearClientOutputSequence() {
      
      clientOutputSequence_ = 0L;
    }

    public static final int BIN_FIELD_NUMBER = 7;
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 7;</code>
     */
    public com.google.protobuf.ByteString getBin() {
      if (bodyCase_ == 7) {
        return (com.google.protobuf.ByteString) body_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 7;</code>
     */
    private void setBin(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 7;
      body_ = value;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 7;</code>
     */
    private void clearBin() {
      if (bodyCase_ == 7) {
        bodyCase_ = 0;
        body_ = null;
      }
    }

    public static final int PONG_FIELD_NUMBER = 8;
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional bytes pong = 8;</code>
     */
    public com.google.protobuf.ByteString getPong() {
      if (bodyCase_ == 8) {
        return (com.google.protobuf.ByteString) body_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional bytes pong = 8;</code>
     */
    private void setPong(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 8;
      body_ = value;
    }
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional bytes pong = 8;</code>
     */
    private void clearPong() {
      if (bodyCase_ == 8) {
        bodyCase_ = 0;
        body_ = null;
      }
    }

    public static final int END_FIELD_NUMBER = 9;
    /**
     * <pre>
     *end with final binary data, nullable
     * </pre>
     *
     * <code>optional bytes end = 9;</code>
     */
    public com.google.protobuf.ByteString getEnd() {
      if (bodyCase_ == 9) {
        return (com.google.protobuf.ByteString) body_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     *end with final binary data, nullable
     * </pre>
     *
     * <code>optional bytes end = 9;</code>
     */
    private void setEnd(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 9;
      body_ = value;
    }
    /**
     * <pre>
     *end with final binary data, nullable
     * </pre>
     *
     * <code>optional bytes end = 9;</code>
     */
    private void clearEnd() {
      if (bodyCase_ == 9) {
        bodyCase_ = 0;
        body_ = null;
      }
    }

    public static final int CANCEL_FIELD_NUMBER = 10;
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 10;</code>
     */
    public java.lang.String getCancel() {
      java.lang.String ref = "";
      if (bodyCase_ == 10) {
        ref = (java.lang.String) body_;
      }
      return ref;
    }
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCancelBytes() {
      java.lang.String ref = "";
      if (bodyCase_ == 10) {
        ref = (java.lang.String) body_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 10;</code>
     */
    private void setCancel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 10;
      body_ = value;
    }
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 10;</code>
     */
    private void clearCancel() {
      if (bodyCase_ == 10) {
        bodyCase_ = 0;
        body_ = null;
      }
    }
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 10;</code>
     */
    private void setCancelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyCase_ = 10;
      body_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0L) {
        output.writeInt64(1, sessionId_);
      }
      if (clientOutputSequence_ != 0L) {
        output.writeInt64(2, clientOutputSequence_);
      }
      if (bodyCase_ == 7) {
        output.writeBytes(
            7, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 8) {
        output.writeBytes(
            8, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 9) {
        output.writeBytes(
            9, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 10) {
        output.writeString(10, getCancel());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      if (clientOutputSequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, clientOutputSequence_);
      }
      if (bodyCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              7, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 8) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              8, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 9) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              9, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) body_));
      }
      if (bodyCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getCancel());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.xy02.raas.Data.ClientOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.xy02.raas.Data.ClientOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.xy02.raas.Data.ClientOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code raas.ClientOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.xy02.raas.Data.ClientOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:raas.ClientOutput)
        com.github.xy02.raas.Data.ClientOutputOrBuilder {
      // Construct using com.github.xy02.raas.Data.ClientOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public BodyCase
          getBodyCase() {
        return instance.getBodyCase();
      }

      public Builder clearBody() {
        copyOnWrite();
        instance.clearBody();
        return this;
      }


      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public long getSessionId() {
        return instance.getSessionId();
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder setSessionId(long value) {
        copyOnWrite();
        instance.setSessionId(value);
        return this;
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        copyOnWrite();
        instance.clearSessionId();
        return this;
      }

      /**
       * <pre>
       *sequence number start from 1
       * </pre>
       *
       * <code>optional int64 client_output_sequence = 2;</code>
       */
      public long getClientOutputSequence() {
        return instance.getClientOutputSequence();
      }
      /**
       * <pre>
       *sequence number start from 1
       * </pre>
       *
       * <code>optional int64 client_output_sequence = 2;</code>
       */
      public Builder setClientOutputSequence(long value) {
        copyOnWrite();
        instance.setClientOutputSequence(value);
        return this;
      }
      /**
       * <pre>
       *sequence number start from 1
       * </pre>
       *
       * <code>optional int64 client_output_sequence = 2;</code>
       */
      public Builder clearClientOutputSequence() {
        copyOnWrite();
        instance.clearClientOutputSequence();
        return this;
      }

      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 7;</code>
       */
      public com.google.protobuf.ByteString getBin() {
        return instance.getBin();
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 7;</code>
       */
      public Builder setBin(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBin(value);
        return this;
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 7;</code>
       */
      public Builder clearBin() {
        copyOnWrite();
        instance.clearBin();
        return this;
      }

      /**
       * <pre>
       *client output PONG message when it get PING
       * </pre>
       *
       * <code>optional bytes pong = 8;</code>
       */
      public com.google.protobuf.ByteString getPong() {
        return instance.getPong();
      }
      /**
       * <pre>
       *client output PONG message when it get PING
       * </pre>
       *
       * <code>optional bytes pong = 8;</code>
       */
      public Builder setPong(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPong(value);
        return this;
      }
      /**
       * <pre>
       *client output PONG message when it get PING
       * </pre>
       *
       * <code>optional bytes pong = 8;</code>
       */
      public Builder clearPong() {
        copyOnWrite();
        instance.clearPong();
        return this;
      }

      /**
       * <pre>
       *end with final binary data, nullable
       * </pre>
       *
       * <code>optional bytes end = 9;</code>
       */
      public com.google.protobuf.ByteString getEnd() {
        return instance.getEnd();
      }
      /**
       * <pre>
       *end with final binary data, nullable
       * </pre>
       *
       * <code>optional bytes end = 9;</code>
       */
      public Builder setEnd(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEnd(value);
        return this;
      }
      /**
       * <pre>
       *end with final binary data, nullable
       * </pre>
       *
       * <code>optional bytes end = 9;</code>
       */
      public Builder clearEnd() {
        copyOnWrite();
        instance.clearEnd();
        return this;
      }

      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 10;</code>
       */
      public java.lang.String getCancel() {
        return instance.getCancel();
      }
      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCancelBytes() {
        return instance.getCancelBytes();
      }
      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 10;</code>
       */
      public Builder setCancel(
          java.lang.String value) {
        copyOnWrite();
        instance.setCancel(value);
        return this;
      }
      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 10;</code>
       */
      public Builder clearCancel() {
        copyOnWrite();
        instance.clearCancel();
        return this;
      }
      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 10;</code>
       */
      public Builder setCancelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCancelBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:raas.ClientOutput)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.xy02.raas.Data.ClientOutput();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.xy02.raas.Data.ClientOutput other = (com.github.xy02.raas.Data.ClientOutput) arg1;
          sessionId_ = visitor.visitLong(sessionId_ != 0L, sessionId_,
              other.sessionId_ != 0L, other.sessionId_);
          clientOutputSequence_ = visitor.visitLong(clientOutputSequence_ != 0L, clientOutputSequence_,
              other.clientOutputSequence_ != 0L, other.clientOutputSequence_);
          switch (other.getBodyCase()) {
            case BIN: {
              body_ = visitor.visitOneofByteString(
                  bodyCase_ == 7, body_, other.body_);
              break;
            }
            case PONG: {
              body_ = visitor.visitOneofByteString(
                  bodyCase_ == 8, body_, other.body_);
              break;
            }
            case END: {
              body_ = visitor.visitOneofByteString(
                  bodyCase_ == 9, body_, other.body_);
              break;
            }
            case CANCEL: {
              body_ = visitor.visitOneofString(
                 bodyCase_ == 10, body_, other.body_);
              break;
            }
            case BODY_NOT_SET: {
              visitor.visitOneofNotSet(bodyCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.bodyCase_ != 0) {
              bodyCase_ = other.bodyCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  sessionId_ = input.readInt64();
                  break;
                }
                case 16: {

                  clientOutputSequence_ = input.readInt64();
                  break;
                }
                case 58: {
                  bodyCase_ = 7;
                  body_ = input.readBytes();
                  break;
                }
                case 66: {
                  bodyCase_ = 8;
                  body_ = input.readBytes();
                  break;
                }
                case 74: {
                  bodyCase_ = 9;
                  body_ = input.readBytes();
                  break;
                }
                case 82: {
                  String s = input.readStringRequireUtf8();
                  bodyCase_ = 10;
                  body_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.xy02.raas.Data.ClientOutput.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:raas.ClientOutput)
    private static final com.github.xy02.raas.Data.ClientOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientOutput();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.xy02.raas.Data.ClientOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ClientOutput> PARSER;

    public static com.google.protobuf.Parser<ClientOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
