// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.github.xy02.raas;

public final class DataOuterClass {
  private DataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raas.Data)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes raw = 1;</code>
     */
    com.google.protobuf.ByteString getRaw();

    /**
     * <pre>
     *""==complete, "err message"==error
     * </pre>
     *
     * <code>optional string final = 2;</code>
     */
    String getFinal();
    /**
     * <pre>
     *""==complete, "err message"==error
     * </pre>
     *
     * <code>optional string final = 2;</code>
     */
    com.google.protobuf.ByteString
        getFinalBytes();

    public Data.TypeCase getTypeCase();
  }
  /**
   * Protobuf type {@code raas.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageLite<
          Data, Data.Builder> implements
      // @@protoc_insertion_point(message_implements:raas.Data)
      DataOrBuilder {
    private Data() {
    }
    private int typeCase_ = 0;
    private Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite {
      RAW(1),
      FINAL(2),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 1: return RAW;
          case 2: return FINAL;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    private void clearType() {
      typeCase_ = 0;
      type_ = null;
    }

    public static final int RAW_FIELD_NUMBER = 1;
    /**
     * <code>optional bytes raw = 1;</code>
     */
    public com.google.protobuf.ByteString getRaw() {
      if (typeCase_ == 1) {
        return (com.google.protobuf.ByteString) type_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>optional bytes raw = 1;</code>
     */
    private void setRaw(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 1;
      type_ = value;
    }
    /**
     * <code>optional bytes raw = 1;</code>
     */
    private void clearRaw() {
      if (typeCase_ == 1) {
        typeCase_ = 0;
        type_ = null;
      }
    }

    public static final int FINAL_FIELD_NUMBER = 2;
    /**
     * <pre>
     *""==complete, "err message"==error
     * </pre>
     *
     * <code>optional string final = 2;</code>
     */
    public String getFinal() {
      String ref = "";
      if (typeCase_ == 2) {
        ref = (String) type_;
      }
      return ref;
    }
    /**
     * <pre>
     *""==complete, "err message"==error
     * </pre>
     *
     * <code>optional string final = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFinalBytes() {
      String ref = "";
      if (typeCase_ == 2) {
        ref = (String) type_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *""==complete, "err message"==error
     * </pre>
     *
     * <code>optional string final = 2;</code>
     */
    private void setFinal(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 2;
      type_ = value;
    }
    /**
     * <pre>
     *""==complete, "err message"==error
     * </pre>
     *
     * <code>optional string final = 2;</code>
     */
    private void clearFinal() {
      if (typeCase_ == 2) {
        typeCase_ = 0;
        type_ = null;
      }
    }
    /**
     * <pre>
     *""==complete, "err message"==error
     * </pre>
     *
     * <code>optional string final = 2;</code>
     */
    private void setFinalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      typeCase_ = 2;
      type_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeCase_ == 1) {
        output.writeBytes(
            1, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) type_));
      }
      if (typeCase_ == 2) {
        output.writeString(2, getFinal());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (typeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              1, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) type_));
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getFinal());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code raas.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Data, Builder> implements
        // @@protoc_insertion_point(builder_implements:raas.Data)
        DataOrBuilder {
      // Construct using com.github.xy02.raas.DataOuterClass.Data.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public TypeCase
          getTypeCase() {
        return instance.getTypeCase();
      }

      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }


      /**
       * <code>optional bytes raw = 1;</code>
       */
      public com.google.protobuf.ByteString getRaw() {
        return instance.getRaw();
      }
      /**
       * <code>optional bytes raw = 1;</code>
       */
      public Builder setRaw(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRaw(value);
        return this;
      }
      /**
       * <code>optional bytes raw = 1;</code>
       */
      public Builder clearRaw() {
        copyOnWrite();
        instance.clearRaw();
        return this;
      }

      /**
       * <pre>
       *""==complete, "err message"==error
       * </pre>
       *
       * <code>optional string final = 2;</code>
       */
      public String getFinal() {
        return instance.getFinal();
      }
      /**
       * <pre>
       *""==complete, "err message"==error
       * </pre>
       *
       * <code>optional string final = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFinalBytes() {
        return instance.getFinalBytes();
      }
      /**
       * <pre>
       *""==complete, "err message"==error
       * </pre>
       *
       * <code>optional string final = 2;</code>
       */
      public Builder setFinal(
          String value) {
        copyOnWrite();
        instance.setFinal(value);
        return this;
      }
      /**
       * <pre>
       *""==complete, "err message"==error
       * </pre>
       *
       * <code>optional string final = 2;</code>
       */
      public Builder clearFinal() {
        copyOnWrite();
        instance.clearFinal();
        return this;
      }
      /**
       * <pre>
       *""==complete, "err message"==error
       * </pre>
       *
       * <code>optional string final = 2;</code>
       */
      public Builder setFinalBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFinalBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:raas.Data)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Data();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Data other = (Data) arg1;
          switch (other.getTypeCase()) {
            case RAW: {
              type_ = visitor.visitOneofByteString(
                  typeCase_ == 1, type_, other.type_);
              break;
            }
            case FINAL: {
              type_ = visitor.visitOneofString(
                 typeCase_ == 2, type_, other.type_);
              break;
            }
            case TYPE_NOT_SET: {
              visitor.visitOneofNotSet(typeCase_ != 0);
              break;
            }
          }
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            if (other.typeCase_ != 0) {
              typeCase_ = other.typeCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  typeCase_ = 1;
                  type_ = input.readBytes();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();
                  typeCase_ = 2;
                  type_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Data.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:raas.Data)
    private static final Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Data();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Data> PARSER;

    public static com.google.protobuf.Parser<Data> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
