// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.github.xy02.raas;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ClientOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raas.ClientOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    long getSessionId();

    /**
     * <pre>
     *one call one request
     * </pre>
     *
     * <code>optional .raas.Request request = 2;</code>
     */
    Request getRequest();

    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 3;</code>
     */
    String getCancel();
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 3;</code>
     */
    com.google.protobuf.ByteString
        getCancelBytes();

    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional string pong = 4;</code>
     */
    String getPong();
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional string pong = 4;</code>
     */
    com.google.protobuf.ByteString
        getPongBytes();

    public ClientOutput.TypeCase getTypeCase();
  }
  /**
   * Protobuf type {@code raas.ClientOutput}
   */
  public  static final class ClientOutput extends
      com.google.protobuf.GeneratedMessageLite<
          ClientOutput, ClientOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:raas.ClientOutput)
      ClientOutputOrBuilder {
    private ClientOutput() {
    }
    private int typeCase_ = 0;
    private Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite {
      REQUEST(2),
      CANCEL(3),
      PONG(4),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 2: return REQUEST;
          case 3: return CANCEL;
          case 4: return PONG;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    private void clearType() {
      typeCase_ = 0;
      type_ = null;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void setSessionId(long value) {
      
      sessionId_ = value;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void clearSessionId() {
      
      sessionId_ = 0L;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    /**
     * <pre>
     *one call one request
     * </pre>
     *
     * <code>optional .raas.Request request = 2;</code>
     */
    public Request getRequest() {
      if (typeCase_ == 2) {
         return (Request) type_;
      }
      return Request.getDefaultInstance();
    }
    /**
     * <pre>
     *one call one request
     * </pre>
     *
     * <code>optional .raas.Request request = 2;</code>
     */
    private void setRequest(Request value) {
      if (value == null) {
        throw new NullPointerException();
      }
      type_ = value;
      typeCase_ = 2;
    }
    /**
     * <pre>
     *one call one request
     * </pre>
     *
     * <code>optional .raas.Request request = 2;</code>
     */
    private void setRequest(
        Request.Builder builderForValue) {
      type_ = builderForValue.build();
      typeCase_ = 2;
    }
    /**
     * <pre>
     *one call one request
     * </pre>
     *
     * <code>optional .raas.Request request = 2;</code>
     */
    private void mergeRequest(Request value) {
      if (typeCase_ == 2 &&
          type_ != Request.getDefaultInstance()) {
        type_ = Request.newBuilder((Request) type_)
            .mergeFrom(value).buildPartial();
      } else {
        type_ = value;
      }
      typeCase_ = 2;
    }
    /**
     * <pre>
     *one call one request
     * </pre>
     *
     * <code>optional .raas.Request request = 2;</code>
     */
    private void clearRequest() {
      if (typeCase_ == 2) {
        typeCase_ = 0;
        type_ = null;
      }
    }

    public static final int CANCEL_FIELD_NUMBER = 3;
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 3;</code>
     */
    public String getCancel() {
      String ref = "";
      if (typeCase_ == 3) {
        ref = (String) type_;
      }
      return ref;
    }
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCancelBytes() {
      String ref = "";
      if (typeCase_ == 3) {
        ref = (String) type_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 3;</code>
     */
    private void setCancel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 3;
      type_ = value;
    }
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 3;</code>
     */
    private void clearCancel() {
      if (typeCase_ == 3) {
        typeCase_ = 0;
        type_ = null;
      }
    }
    /**
     * <pre>
     *cancel request
     * </pre>
     *
     * <code>optional string cancel = 3;</code>
     */
    private void setCancelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      typeCase_ = 3;
      type_ = value.toStringUtf8();
    }

    public static final int PONG_FIELD_NUMBER = 4;
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional string pong = 4;</code>
     */
    public String getPong() {
      String ref = "";
      if (typeCase_ == 4) {
        ref = (String) type_;
      }
      return ref;
    }
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional string pong = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPongBytes() {
      String ref = "";
      if (typeCase_ == 4) {
        ref = (String) type_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional string pong = 4;</code>
     */
    private void setPong(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 4;
      type_ = value;
    }
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional string pong = 4;</code>
     */
    private void clearPong() {
      if (typeCase_ == 4) {
        typeCase_ = 0;
        type_ = null;
      }
    }
    /**
     * <pre>
     *client output PONG message when it get PING
     * </pre>
     *
     * <code>optional string pong = 4;</code>
     */
    private void setPongBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      typeCase_ = 4;
      type_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0L) {
        output.writeInt64(1, sessionId_);
      }
      if (typeCase_ == 2) {
        output.writeMessage(2, (Request) type_);
      }
      if (typeCase_ == 3) {
        output.writeString(3, getCancel());
      }
      if (typeCase_ == 4) {
        output.writeString(4, getPong());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Request) type_);
      }
      if (typeCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getCancel());
      }
      if (typeCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getPong());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ClientOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ClientOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ClientOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ClientOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ClientOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ClientOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ClientOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ClientOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ClientOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ClientOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code raas.ClientOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ClientOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:raas.ClientOutput)
        ClientOutputOrBuilder {
      // Construct using com.github.xy02.raas.Data.ClientOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public TypeCase
          getTypeCase() {
        return instance.getTypeCase();
      }

      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }


      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public long getSessionId() {
        return instance.getSessionId();
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder setSessionId(long value) {
        copyOnWrite();
        instance.setSessionId(value);
        return this;
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        copyOnWrite();
        instance.clearSessionId();
        return this;
      }

      /**
       * <pre>
       *one call one request
       * </pre>
       *
       * <code>optional .raas.Request request = 2;</code>
       */
      public Request getRequest() {
        return instance.getRequest();
      }
      /**
       * <pre>
       *one call one request
       * </pre>
       *
       * <code>optional .raas.Request request = 2;</code>
       */
      public Builder setRequest(Request value) {
        copyOnWrite();
        instance.setRequest(value);
        return this;
      }
      /**
       * <pre>
       *one call one request
       * </pre>
       *
       * <code>optional .raas.Request request = 2;</code>
       */
      public Builder setRequest(
          Request.Builder builderForValue) {
        copyOnWrite();
        instance.setRequest(builderForValue);
        return this;
      }
      /**
       * <pre>
       *one call one request
       * </pre>
       *
       * <code>optional .raas.Request request = 2;</code>
       */
      public Builder mergeRequest(Request value) {
        copyOnWrite();
        instance.mergeRequest(value);
        return this;
      }
      /**
       * <pre>
       *one call one request
       * </pre>
       *
       * <code>optional .raas.Request request = 2;</code>
       */
      public Builder clearRequest() {
        copyOnWrite();
        instance.clearRequest();
        return this;
      }

      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 3;</code>
       */
      public String getCancel() {
        return instance.getCancel();
      }
      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCancelBytes() {
        return instance.getCancelBytes();
      }
      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 3;</code>
       */
      public Builder setCancel(
          String value) {
        copyOnWrite();
        instance.setCancel(value);
        return this;
      }
      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 3;</code>
       */
      public Builder clearCancel() {
        copyOnWrite();
        instance.clearCancel();
        return this;
      }
      /**
       * <pre>
       *cancel request
       * </pre>
       *
       * <code>optional string cancel = 3;</code>
       */
      public Builder setCancelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCancelBytes(value);
        return this;
      }

      /**
       * <pre>
       *client output PONG message when it get PING
       * </pre>
       *
       * <code>optional string pong = 4;</code>
       */
      public String getPong() {
        return instance.getPong();
      }
      /**
       * <pre>
       *client output PONG message when it get PING
       * </pre>
       *
       * <code>optional string pong = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPongBytes() {
        return instance.getPongBytes();
      }
      /**
       * <pre>
       *client output PONG message when it get PING
       * </pre>
       *
       * <code>optional string pong = 4;</code>
       */
      public Builder setPong(
          String value) {
        copyOnWrite();
        instance.setPong(value);
        return this;
      }
      /**
       * <pre>
       *client output PONG message when it get PING
       * </pre>
       *
       * <code>optional string pong = 4;</code>
       */
      public Builder clearPong() {
        copyOnWrite();
        instance.clearPong();
        return this;
      }
      /**
       * <pre>
       *client output PONG message when it get PING
       * </pre>
       *
       * <code>optional string pong = 4;</code>
       */
      public Builder setPongBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPongBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:raas.ClientOutput)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ClientOutput();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ClientOutput other = (ClientOutput) arg1;
          sessionId_ = visitor.visitLong(sessionId_ != 0L, sessionId_,
              other.sessionId_ != 0L, other.sessionId_);
          switch (other.getTypeCase()) {
            case REQUEST: {
              type_ = visitor.visitOneofMessage(
                  typeCase_ == 2,
                  type_,
                  other.type_);
              break;
            }
            case CANCEL: {
              type_ = visitor.visitOneofString(
                 typeCase_ == 3, type_, other.type_);
              break;
            }
            case PONG: {
              type_ = visitor.visitOneofString(
                 typeCase_ == 4, type_, other.type_);
              break;
            }
            case TYPE_NOT_SET: {
              visitor.visitOneofNotSet(typeCase_ != 0);
              break;
            }
          }
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            if (other.typeCase_ != 0) {
              typeCase_ = other.typeCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  sessionId_ = input.readInt64();
                  break;
                }
                case 18: {
                  Request.Builder subBuilder = null;
                  if (typeCase_ == 2) {
                    subBuilder = ((Request) type_).toBuilder();
                  }
                  type_ =
                       input.readMessage(Request.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((Request) type_);
                    type_ = subBuilder.buildPartial();
                  }
                  typeCase_ = 2;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();
                  typeCase_ = 3;
                  type_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();
                  typeCase_ = 4;
                  type_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ClientOutput.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:raas.ClientOutput)
    private static final ClientOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientOutput();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ClientOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ClientOutput> PARSER;

    public static com.google.protobuf.Parser<ClientOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raas.Request)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 1;</code>
     */
    String getClientId();
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 2;</code>
     */
    com.google.protobuf.ByteString getBin();
  }
  /**
   * Protobuf type {@code raas.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageLite<
          Request, Request.Builder> implements
      // @@protoc_insertion_point(message_implements:raas.Request)
      RequestOrBuilder {
    private Request() {
      clientId_ = "";
      bin_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int CLIENT_ID_FIELD_NUMBER = 1;
    private String clientId_;
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 1;</code>
     */
    public String getClientId() {
      return clientId_;
    }
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(clientId_);
    }
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 1;</code>
     */
    private void setClientId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
    }
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 1;</code>
     */
    private void clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
    }
    /**
     * <pre>
     *client id
     * </pre>
     *
     * <code>optional string client_id = 1;</code>
     */
    private void setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value.toStringUtf8();
    }

    public static final int BIN_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bin_;
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 2;</code>
     */
    public com.google.protobuf.ByteString getBin() {
      return bin_;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 2;</code>
     */
    private void setBin(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bin_ = value;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 2;</code>
     */
    private void clearBin() {
      
      bin_ = getDefaultInstance().getBin();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!clientId_.isEmpty()) {
        output.writeString(1, getClientId());
      }
      if (!bin_.isEmpty()) {
        output.writeBytes(2, bin_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!clientId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getClientId());
      }
      if (!bin_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bin_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code raas.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Request, Builder> implements
        // @@protoc_insertion_point(builder_implements:raas.Request)
        RequestOrBuilder {
      // Construct using com.github.xy02.raas.Data.Request.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 1;</code>
       */
      public String getClientId() {
        return instance.getClientId();
      }
      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        return instance.getClientIdBytes();
      }
      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 1;</code>
       */
      public Builder setClientId(
          String value) {
        copyOnWrite();
        instance.setClientId(value);
        return this;
      }
      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 1;</code>
       */
      public Builder clearClientId() {
        copyOnWrite();
        instance.clearClientId();
        return this;
      }
      /**
       * <pre>
       *client id
       * </pre>
       *
       * <code>optional string client_id = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 2;</code>
       */
      public com.google.protobuf.ByteString getBin() {
        return instance.getBin();
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 2;</code>
       */
      public Builder setBin(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBin(value);
        return this;
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 2;</code>
       */
      public Builder clearBin() {
        copyOnWrite();
        instance.clearBin();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:raas.Request)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Request();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Request other = (Request) arg1;
          clientId_ = visitor.visitString(!clientId_.isEmpty(), clientId_,
              !other.clientId_.isEmpty(), other.clientId_);
          bin_ = visitor.visitByteString(bin_ != com.google.protobuf.ByteString.EMPTY, bin_,
              other.bin_ != com.google.protobuf.ByteString.EMPTY, other.bin_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  clientId_ = s;
                  break;
                }
                case 18: {

                  bin_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Request.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:raas.Request)
    private static final Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Request();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Request> PARSER;

    public static com.google.protobuf.Parser<Request> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ServerOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raas.ServerOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    long getSessionId();

    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>optional string server_id = 2;</code>
     */
    String getServerId();
    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>optional string server_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getServerIdBytes();

    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 3;</code>
     */
    com.google.protobuf.ByteString getBin();

    /**
     * <pre>
     *""(empty string) means complete, "err message"(not empty) means error
     * </pre>
     *
     * <code>optional string final = 4;</code>
     */
    String getFinal();
    /**
     * <pre>
     *""(empty string) means complete, "err message"(not empty) means error
     * </pre>
     *
     * <code>optional string final = 4;</code>
     */
    com.google.protobuf.ByteString
        getFinalBytes();

    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional string ping = 5;</code>
     */
    String getPing();
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional string ping = 5;</code>
     */
    com.google.protobuf.ByteString
        getPingBytes();

    public ServerOutput.TypeCase getTypeCase();
  }
  /**
   * Protobuf type {@code raas.ServerOutput}
   */
  public  static final class ServerOutput extends
      com.google.protobuf.GeneratedMessageLite<
          ServerOutput, ServerOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:raas.ServerOutput)
      ServerOutputOrBuilder {
    private ServerOutput() {
    }
    private int typeCase_ = 0;
    private Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite {
      SERVER_ID(2),
      BIN(3),
      FINAL(4),
      PING(5),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 2: return SERVER_ID;
          case 3: return BIN;
          case 4: return FINAL;
          case 5: return PING;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    private void clearType() {
      typeCase_ = 0;
      type_ = null;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void setSessionId(long value) {
      
      sessionId_ = value;
    }
    /**
     * <pre>
     *session id
     * </pre>
     *
     * <code>optional int64 session_id = 1;</code>
     */
    private void clearSessionId() {
      
      sessionId_ = 0L;
    }

    public static final int SERVER_ID_FIELD_NUMBER = 2;
    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>optional string server_id = 2;</code>
     */
    public String getServerId() {
      String ref = "";
      if (typeCase_ == 2) {
        ref = (String) type_;
      }
      return ref;
    }
    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>optional string server_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      String ref = "";
      if (typeCase_ == 2) {
        ref = (String) type_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>optional string server_id = 2;</code>
     */
    private void setServerId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 2;
      type_ = value;
    }
    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>optional string server_id = 2;</code>
     */
    private void clearServerId() {
      if (typeCase_ == 2) {
        typeCase_ = 0;
        type_ = null;
      }
    }
    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>optional string server_id = 2;</code>
     */
    private void setServerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      typeCase_ = 2;
      type_ = value.toStringUtf8();
    }

    public static final int BIN_FIELD_NUMBER = 3;
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 3;</code>
     */
    public com.google.protobuf.ByteString getBin() {
      if (typeCase_ == 3) {
        return (com.google.protobuf.ByteString) type_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 3;</code>
     */
    private void setBin(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 3;
      type_ = value;
    }
    /**
     * <pre>
     *raw binary data
     * </pre>
     *
     * <code>optional bytes bin = 3;</code>
     */
    private void clearBin() {
      if (typeCase_ == 3) {
        typeCase_ = 0;
        type_ = null;
      }
    }

    public static final int FINAL_FIELD_NUMBER = 4;
    /**
     * <pre>
     *""(empty string) means complete, "err message"(not empty) means error
     * </pre>
     *
     * <code>optional string final = 4;</code>
     */
    public String getFinal() {
      String ref = "";
      if (typeCase_ == 4) {
        ref = (String) type_;
      }
      return ref;
    }
    /**
     * <pre>
     *""(empty string) means complete, "err message"(not empty) means error
     * </pre>
     *
     * <code>optional string final = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFinalBytes() {
      String ref = "";
      if (typeCase_ == 4) {
        ref = (String) type_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *""(empty string) means complete, "err message"(not empty) means error
     * </pre>
     *
     * <code>optional string final = 4;</code>
     */
    private void setFinal(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 4;
      type_ = value;
    }
    /**
     * <pre>
     *""(empty string) means complete, "err message"(not empty) means error
     * </pre>
     *
     * <code>optional string final = 4;</code>
     */
    private void clearFinal() {
      if (typeCase_ == 4) {
        typeCase_ = 0;
        type_ = null;
      }
    }
    /**
     * <pre>
     *""(empty string) means complete, "err message"(not empty) means error
     * </pre>
     *
     * <code>optional string final = 4;</code>
     */
    private void setFinalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      typeCase_ = 4;
      type_ = value.toStringUtf8();
    }

    public static final int PING_FIELD_NUMBER = 5;
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional string ping = 5;</code>
     */
    public String getPing() {
      String ref = "";
      if (typeCase_ == 5) {
        ref = (String) type_;
      }
      return ref;
    }
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional string ping = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPingBytes() {
      String ref = "";
      if (typeCase_ == 5) {
        ref = (String) type_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional string ping = 5;</code>
     */
    private void setPing(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 5;
      type_ = value;
    }
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional string ping = 5;</code>
     */
    private void clearPing() {
      if (typeCase_ == 5) {
        typeCase_ = 0;
        type_ = null;
      }
    }
    /**
     * <pre>
     *PING
     * </pre>
     *
     * <code>optional string ping = 5;</code>
     */
    private void setPingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      typeCase_ = 5;
      type_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0L) {
        output.writeInt64(1, sessionId_);
      }
      if (typeCase_ == 2) {
        output.writeString(2, getServerId());
      }
      if (typeCase_ == 3) {
        output.writeBytes(
            3, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) type_));
      }
      if (typeCase_ == 4) {
        output.writeString(4, getFinal());
      }
      if (typeCase_ == 5) {
        output.writeString(5, getPing());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getServerId());
      }
      if (typeCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              3, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) type_));
      }
      if (typeCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getFinal());
      }
      if (typeCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getPing());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ServerOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ServerOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ServerOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ServerOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ServerOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ServerOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ServerOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ServerOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ServerOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ServerOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServerOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code raas.ServerOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ServerOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:raas.ServerOutput)
        ServerOutputOrBuilder {
      // Construct using com.github.xy02.raas.Data.ServerOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public TypeCase
          getTypeCase() {
        return instance.getTypeCase();
      }

      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }


      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public long getSessionId() {
        return instance.getSessionId();
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder setSessionId(long value) {
        copyOnWrite();
        instance.setSessionId(value);
        return this;
      }
      /**
       * <pre>
       *session id
       * </pre>
       *
       * <code>optional int64 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        copyOnWrite();
        instance.clearSessionId();
        return this;
      }

      /**
       * <pre>
       *server id
       * </pre>
       *
       * <code>optional string server_id = 2;</code>
       */
      public String getServerId() {
        return instance.getServerId();
      }
      /**
       * <pre>
       *server id
       * </pre>
       *
       * <code>optional string server_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServerIdBytes() {
        return instance.getServerIdBytes();
      }
      /**
       * <pre>
       *server id
       * </pre>
       *
       * <code>optional string server_id = 2;</code>
       */
      public Builder setServerId(
          String value) {
        copyOnWrite();
        instance.setServerId(value);
        return this;
      }
      /**
       * <pre>
       *server id
       * </pre>
       *
       * <code>optional string server_id = 2;</code>
       */
      public Builder clearServerId() {
        copyOnWrite();
        instance.clearServerId();
        return this;
      }
      /**
       * <pre>
       *server id
       * </pre>
       *
       * <code>optional string server_id = 2;</code>
       */
      public Builder setServerIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServerIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 3;</code>
       */
      public com.google.protobuf.ByteString getBin() {
        return instance.getBin();
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 3;</code>
       */
      public Builder setBin(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBin(value);
        return this;
      }
      /**
       * <pre>
       *raw binary data
       * </pre>
       *
       * <code>optional bytes bin = 3;</code>
       */
      public Builder clearBin() {
        copyOnWrite();
        instance.clearBin();
        return this;
      }

      /**
       * <pre>
       *""(empty string) means complete, "err message"(not empty) means error
       * </pre>
       *
       * <code>optional string final = 4;</code>
       */
      public String getFinal() {
        return instance.getFinal();
      }
      /**
       * <pre>
       *""(empty string) means complete, "err message"(not empty) means error
       * </pre>
       *
       * <code>optional string final = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFinalBytes() {
        return instance.getFinalBytes();
      }
      /**
       * <pre>
       *""(empty string) means complete, "err message"(not empty) means error
       * </pre>
       *
       * <code>optional string final = 4;</code>
       */
      public Builder setFinal(
          String value) {
        copyOnWrite();
        instance.setFinal(value);
        return this;
      }
      /**
       * <pre>
       *""(empty string) means complete, "err message"(not empty) means error
       * </pre>
       *
       * <code>optional string final = 4;</code>
       */
      public Builder clearFinal() {
        copyOnWrite();
        instance.clearFinal();
        return this;
      }
      /**
       * <pre>
       *""(empty string) means complete, "err message"(not empty) means error
       * </pre>
       *
       * <code>optional string final = 4;</code>
       */
      public Builder setFinalBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFinalBytes(value);
        return this;
      }

      /**
       * <pre>
       *PING
       * </pre>
       *
       * <code>optional string ping = 5;</code>
       */
      public String getPing() {
        return instance.getPing();
      }
      /**
       * <pre>
       *PING
       * </pre>
       *
       * <code>optional string ping = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPingBytes() {
        return instance.getPingBytes();
      }
      /**
       * <pre>
       *PING
       * </pre>
       *
       * <code>optional string ping = 5;</code>
       */
      public Builder setPing(
          String value) {
        copyOnWrite();
        instance.setPing(value);
        return this;
      }
      /**
       * <pre>
       *PING
       * </pre>
       *
       * <code>optional string ping = 5;</code>
       */
      public Builder clearPing() {
        copyOnWrite();
        instance.clearPing();
        return this;
      }
      /**
       * <pre>
       *PING
       * </pre>
       *
       * <code>optional string ping = 5;</code>
       */
      public Builder setPingBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPingBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:raas.ServerOutput)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ServerOutput();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ServerOutput other = (ServerOutput) arg1;
          sessionId_ = visitor.visitLong(sessionId_ != 0L, sessionId_,
              other.sessionId_ != 0L, other.sessionId_);
          switch (other.getTypeCase()) {
            case SERVER_ID: {
              type_ = visitor.visitOneofString(
                 typeCase_ == 2, type_, other.type_);
              break;
            }
            case BIN: {
              type_ = visitor.visitOneofByteString(
                  typeCase_ == 3, type_, other.type_);
              break;
            }
            case FINAL: {
              type_ = visitor.visitOneofString(
                 typeCase_ == 4, type_, other.type_);
              break;
            }
            case PING: {
              type_ = visitor.visitOneofString(
                 typeCase_ == 5, type_, other.type_);
              break;
            }
            case TYPE_NOT_SET: {
              visitor.visitOneofNotSet(typeCase_ != 0);
              break;
            }
          }
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            if (other.typeCase_ != 0) {
              typeCase_ = other.typeCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  sessionId_ = input.readInt64();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();
                  typeCase_ = 2;
                  type_ = s;
                  break;
                }
                case 26: {
                  typeCase_ = 3;
                  type_ = input.readBytes();
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();
                  typeCase_ = 4;
                  type_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();
                  typeCase_ = 5;
                  type_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ServerOutput.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:raas.ServerOutput)
    private static final ServerOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServerOutput();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ServerOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ServerOutput> PARSER;

    public static com.google.protobuf.Parser<ServerOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
